import mongoose from 'mongoose';

const contactRequestSchema=new mongoose.Schema({requesterProfile:{type:mongoose.Schema.Types.ObjectId,ref:'MatrimonialProfile',required:true},receiverProfile:{type:mongoose.Schema.Types.ObjectId,ref:'MatrimonialProfile',required:true},status:{type:String,enum:['Pending','Accepted','Declined'],default:'Pending'},respondedAt:Date},{timestamps:true});
contactRequestSchema.index({requesterProfile:1,receiverProfile:1},{unique:true});
const usageSchema=new mongoose.Schema({user:{type:mongoose.Schema.Types.ObjectId,ref:'User',required:true},subscription:{type:mongoose.Schema.Types.ObjectId,ref:'Subscription'},periodStart:{type:Date,required:true},periodEnd:{type:Date,required:true},interestsUsed:{type:Number,default:0},contactViewsUsed:{type:Number,default:0}},{timestamps:true});
usageSchema.index({user:1,periodStart:1,periodEnd:1},{unique:true});
const profileViewSchema=new mongoose.Schema({viewerProfile:{type:mongoose.Schema.Types.ObjectId,ref:'MatrimonialProfile',required:true},viewedProfile:{type:mongoose.Schema.Types.ObjectId,ref:'MatrimonialProfile',required:true},viewDate:{type:Date,default:Date.now}},{timestamps:true});
profileViewSchema.index({viewerProfile:1,viewedProfile:1,viewDate:-1});
const supportTicketSchema=new mongoose.Schema({name:{type:String,required:true,trim:true,maxLength:100},email:{type:String,required:true,lowercase:true,trim:true},phone:String,category:{type:String,enum:['Account','Profile','Payment','Safety','Technical','Other'],required:true},message:{type:String,required:true,minLength:10,maxLength:3000},status:{type:String,enum:['Open','In Progress','Resolved','Closed'],default:'Open'},assignedTo:{type:mongoose.Schema.Types.ObjectId,ref:'User'},resolutionNotes:{type:String,maxLength:2000}},{timestamps:true});
const settingsSchema=new mongoose.Schema({_id:{type:String,default:'global'},platformName:{type:String,default:'Kshatriya Matrimonial Society'},supportEmail:String,supportPhone:String,maintenanceMode:{type:Boolean,default:false},registrationEnabled:{type:Boolean,default:true},paymentsEnabled:{type:Boolean,default:true},maxPhotos:{type:Number,default:6},defaultCountry:{type:String,default:'India'}},{timestamps:true});
const auditSchema=new mongoose.Schema({actor:{type:mongoose.Schema.Types.ObjectId,ref:'User'},action:{type:String,required:true},entityType:String,entityId:String,metadata:mongoose.Schema.Types.Mixed,requestId:String},{timestamps:true});
const preferencesSchema=new mongoose.Schema({user:{type:mongoose.Schema.Types.ObjectId,ref:'User',unique:true,required:true},emailInterests:{type:Boolean,default:true},emailMatches:{type:Boolean,default:true},emailPayments:{type:Boolean,default:true},smsCritical:{type:Boolean,default:true},whatsappFuture:{type:Boolean,default:false}},{timestamps:true});
const resetSchema=new mongoose.Schema({user:{type:mongoose.Schema.Types.ObjectId,ref:'User',required:true,index:true},codeHash:{type:String,required:true},expiresAt:{type:Date,required:true,expires:0},attempts:{type:Number,default:0},usedAt:Date},{timestamps:true});
export const ContactRequest=mongoose.model('ContactRequest',contactRequestSchema);
export const PlanUsage=mongoose.model('PlanUsage',usageSchema);
export const ProfileView=mongoose.model('ProfileView',profileViewSchema);
export const SupportTicket=mongoose.model('SupportTicket',supportTicketSchema);
export const SystemSetting=mongoose.model('SystemSetting',settingsSchema);
export const AuditLog=mongoose.model('AuditLog',auditSchema);
export const NotificationPreference=mongoose.model('NotificationPreference',preferencesSchema);
export const PasswordReset=mongoose.model('PasswordReset',resetSchema);
