import mongoose from 'mongoose';import Counter from './Counter.js';
const privacy={photoVisibility:{type:String,enum:['Everyone','RegisteredMembers','AcceptedInterests','Private'],default:'RegisteredMembers'},contactVisibility:{type:String,enum:['AcceptedInterests','MutualMatches','Private'],default:'MutualMatches'},incomeVisibility:{type:String,enum:['Everyone','RegisteredMembers','AcceptedInterests','Private'],default:'Private'},familyVisibility:{type:String,enum:['RegisteredMembers','AcceptedInterests','Private'],default:'RegisteredMembers'},fullNameVisibility:{type:String,enum:['Everyone','RegisteredMembers'],default:'RegisteredMembers'}};
const schema=new mongoose.Schema({
 userId:{type:mongoose.Schema.Types.ObjectId,ref:'User',required:true,index:true},profileFor:{type:String,enum:['Self','Son','Daughter','Brother','Sister','Relative'],required:true},profileId:{type:String,unique:true,index:true},firstName:{type:String,trim:true,required:true},middleName:String,lastName:String,gender:{type:String,enum:['Male','Female']},dateOfBirth:Date,height:Number,maritalStatus:String,
 location:{city:String,district:String,state:String,country:{type:String,default:'India'},nativePlace:String},community:{name:String,subCommunity:String,clan:String,familyOrigin:String},education:{highestEducation:String,degree:String,specialization:String,college:String,educationDetails:String},career:{occupationType:String,occupation:String,designation:String,companyName:String,businessName:String,annualIncome:Number,incomeVisibility:Boolean},lifestyle:{diet:String,smoking:String,drinking:String,interests:[String]},family:{fatherName:String,fatherOccupation:String,motherName:String,motherOccupation:String,siblings:String,familyType:String,familyLocation:String,familyDescription:String},marriageTimeline:String,aboutMe:String,profilePhoto:String,profilePhotoPublicId:String,gallery:[String],galleryAssets:[{url:String,publicId:String}],boostedUntil:Date,lastBoostAt:Date,verification:{mobileVerified:Boolean,emailVerified:Boolean,photoVerified:Boolean,adminVerified:Boolean},privacy,
 visibility:{type:String,enum:['draft','pending_review','active','changes_required','rejected','paused','hidden'],default:'draft'},lifecycleStatus:{type:String,enum:['Active','Paused','Married','Deleted'],default:'Active'},completionPercentage:{type:Number,default:0},moderationNotes:String,moderatedBy:{type:mongoose.Schema.Types.ObjectId,ref:'User'},moderatedAt:Date,lastActiveAt:Date
},{timestamps:true});
schema.pre('validate',async function(){if(!this.profileId){let counter=await Counter.findById('profileId');if(!counter){const last=await this.constructor.findOne({profileId:/^KSM\d+$/},'profileId').sort({profileId:-1}).lean();try{await Counter.create({_id:'profileId',sequence:Number(last?.profileId?.slice(3))||100000})}catch{/* another request created the counter */}}counter=await Counter.findByIdAndUpdate('profileId',{$inc:{sequence:1}},{returnDocument:'after'});this.profileId=`KSM${counter.sequence}`}});
export default mongoose.model('MatrimonialProfile',schema);
