import {Search,SlidersHorizontal} from 'lucide-react';
import {useEffect,useState} from 'react';
import {useSearchParams} from 'react-router-dom';
import ProfileCard from '../components/ui/ProfileCard';
import {api} from '../services/api';
import {useToast} from '../context/ToastContext';
/* eslint-disable react-hooks/set-state-in-effect, react-hooks/exhaustive-deps */
const initial={search:'',city:'',state:'',lookingFor:'',ageMin:'',ageMax:'',heightMin:'',heightMax:'',education:'',occupation:'',maritalStatus:'',verified:false,withPhoto:false};
export default function DiscoverPage(){
  const [params]=useSearchParams();const fromUrl={...initial,...Object.fromEntries(params.entries())};
  const [filters,setFilters]=useState(fromUrl),[show,setShow]=useState(false),[items,setItems]=useState([]),[pagination,setPagination]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState('');const notify=useToast();
  const load=async(current=filters,page=1)=>{setLoading(true);setError('');try{const q=new URLSearchParams({...Object.fromEntries(Object.entries(current).filter(([,v])=>v!==''&&v!==false)),page:String(page),limit:'12'}).toString();const result=(await api(`/profiles/discover?${q}`)).data;setItems(page===1?result.profiles:x=>[...x,...result.profiles]);setPagination(result.pagination)}catch(e){setError(e.message)}finally{setLoading(false)}};
  useEffect(()=>{load(fromUrl)},[]);const update=(key,value)=>setFilters(f=>({...f,[key]:value}));
  const shortlist=async p=>{try{if(p.shortlisted){await api(`/shortlist/${p._id}`,{method:'DELETE'})}else await api('/shortlist',{method:'POST',body:JSON.stringify({profileId:p._id})});setItems(x=>x.map(i=>i._id===p._id?{...i,shortlisted:!i.shortlisted}:i));notify(p.shortlisted?'Removed from shortlist.':'Profile shortlisted.')}catch(e){notify(e.message,'error')}};
  const interest=async p=>{try{await api('/interests',{method:'POST',body:JSON.stringify({receiverProfile:p._id})});setItems(x=>x.map(i=>i._id===p._id?{...i,interestSent:true}:i));notify('Interest sent.')}catch(e){notify(e.message,'error')}};
  return <><header className="page-heading compact"><p className="eyebrow">Preference-based discovery</p><h1>Discover with <em>intention.</em></h1><p>Compatibility reflects shared preferences—not a prediction of relationship success.</p></header><form onSubmit={e=>{e.preventDefault();load()}} className="discover-toolbar"><label><Search size={18}/><input value={filters.search} onChange={e=>update('search',e.target.value)} placeholder="Search by name, city or profession"/></label><button type="button" onClick={()=>setShow(!show)}><SlidersHorizontal size={17}/> Filters</button></form><div className="discover-layout"><aside className={`filters ${show?'show':''}`}><h3>Refine results</h3><label>Looking for<select value={filters.lookingFor} onChange={e=>update('lookingFor',e.target.value)}><option value="">My preference</option><option>Female</option><option>Male</option></select></label>{[['city','City'],['state','State'],['education','Education'],['occupation','Occupation'],['maritalStatus','Marital status']].map(([k,l])=><label key={k}>{l}<input value={filters[k]} onChange={e=>update(k,e.target.value)}/></label>)}<div className="form-row"><label>Min age<input type="number" value={filters.ageMin} onChange={e=>update('ageMin',e.target.value)}/></label><label>Max age<input type="number" value={filters.ageMax} onChange={e=>update('ageMax',e.target.value)}/></label></div><label className="check"><input type="checkbox" checked={filters.verified} onChange={e=>update('verified',e.target.checked)}/> Verified only</label><label className="check"><input type="checkbox" checked={filters.withPhoto} onChange={e=>update('withPhoto',e.target.checked)}/> With photograph</label><button className="primary-button">Apply filters</button><button type="button" className="text-link" onClick={()=>{setFilters(initial);load(initial)}}>Reset filters</button></aside><section><p className="results-count">{pagination?.total??items.length} thoughtful introductions</p>{loading&&!items.length?<div className="page-skeleton">Finding suitable profiles…</div>:error?<div className="empty-state"><h2>Discovery unavailable</h2><p>{error}</p></div>:items.length?<><div className="profile-grid two">{items.map(p=><ProfileCard key={p.profileId} profile={p} onShortlist={shortlist} onInterest={interest}/>)}</div>{pagination?.page<pagination?.totalPages&&<button className="outline-button load-more" disabled={loading} onClick={()=>load(filters,pagination.page+1)}>{loading?'Loading…':'Load more profiles'}</button>}</>:<div className="empty-state"><h2>No profiles found</h2><p>Try widening the filters to see more suitable introductions.</p></div>}</section></div></>;
}
